### ISSUE TITLE
Make license field accept only one value

### ISSUE THREAD

**Issue by reliztrent** [gwu-libraries/batch-loader#13]
license2, license3, etc should not be allowed. 

(This may simply be something specified in the documentation.)

**Comment by kerchner** [comment]
Currently the GWSS application allows for multiple license values (as this is a Hyrax default).  The batch loader may not be the best place to put GWSS-specific business rules.   May be best to implement this as more of a guideline/practice for uploading items to GWSS in general, whether through the UI or through the batch loader.

Closing ticket for now.
