### ISSUE TITLE
Blank files column uploads all files in "." when in update mode

### ISSUE THREAD

**Issue by reliztrent** [gwu-libraries/batch-loader#15]
**If the upload csv:**
- Has an object ID in "object_id"
- Has no value in "files"
- Has values filled out in all other required fields

e.g.:

files | title1 | creator1 | resource_type1 | license1 | first_file | object_id | keyword1 | keyword2
-- | -- | -- | -- | -- | -- | -- | -- | --
  | test title | test creator | Meeting Minutes | http://www.europeana.eu/portal/rights/rr-r.html | /home/racheltrent/batch-upload/faculty_senate_minutes/1960s/1961_1962_Faculty_Senate_Minutes/Faculty_Senate_Minutes_1961_01_13.pdf | gb19f6221 | I'm a keyword | I'm also a keyword

**Then:**
- The uploader will upload all files (recursively) in "." (relative to the csv file) -- meaning all files in the same directory as the csv will be uploaded to the object.

**Comment by kerchner** [comment]
Requires https://github.com/gwu-libraries/scholarspace-hyrax/issues/189
