### ISSUE TITLE
Batch loader for updates: do we need all required fields, including files?

### ISSUE THREAD

**Issue by dolsysmith** [gwu-libraries/batch-loader#24]
If using the batch loader to update existing records, given the object_id for each record, is it necessary to include all the required fields, when those are not to be changed? It might significantly reduce upload time if we could omit the files on making updates to metadata fields.

**Comment by kerchner** [comment]
If you are updating an existing record (so `object_id` is populated) AND you leave `first_file` empty, then the batch loader will invoke the rails task using the `--skip-file-updates` option.  I'll update the README accordingly.

**Comment by kerchner** [comment]
README has been updated. Closing issue.
