### ISSUE TITLE
object_id field is required, even if blank

### ISSUE THREAD

**Issue by dolsysmith** [gwu-libraries/batch-loader#25]
Although the documentation suggests that the object_id field is optional, when running the batch-loader on a CSV without that column heading (on the test server), I get an error message to the effect that the key 'object_id' can't be found. Adding it to the CSV as an empty column resolves the problem.

I suggest updating the documentation.

**Comment by kerchner** [comment]
Fixed in https://github.com/gwu-libraries/batch-loader/commit/d5b9aad838cd3536041dba22a435b13f0e8536d9
