### ISSUE TITLE
Rights statement for "No known copyright" actually displays "In copyright"

### ISSUE THREAD

**Issue by dolsysmith** [gwu-libraries/batch-loader#26]
rights_statement was populated with http://rightsstatements.org/vocab/NKC/1.0/ for "No known copyright," but the resulting records in GWSS have "In copyright" in the rights field.

**Comment by kerchner** [comment]
Ref https://github.com/gwu-libraries/scholarspace-hyrax/issues/229

**Comment by kerchner** [comment]
Fixed in https://github.com/gwu-libraries/scholarspace-hyrax/issues/229 , deployed with GWSS 1.2.2 https://github.com/gwu-libraries/scholarspace-hyrax/releases/tag/1.2.2
